import 'package:flutter/material.dart';
import '../services/api.dart';
import '../services/session.dart';
import '../widgets/verified_badge.dart';

class AddContactPage extends StatefulWidget { final Session session; const AddContactPage({super.key,required this.session}); @override State<AddContactPage> createState()=>_AddContactPageState(); }
class _AddContactPageState extends State<AddContactPage>{final api=Api();final name=TextEditingController();final username=TextEditingController();Map<String,dynamic>? user;bool searching=false,saving=false;String? error;
 Future<void> find()async{final u=username.text.trim().toLowerCase();if(u.isEmpty)return;setState(()=>searching=true);try{user=await api.findUser(widget.session.token!,u);error=null;}catch(e){user=null;error='Username tidak ditemukan';}if(mounted)setState(()=>searching=false);}
 Future<void> save()async{if(user==null)return;setState(()=>saving=true);try{final target=user!['username'].toString().toLowerCase();final existing=await api.contacts(widget.session.token!);final already=existing.any((e)=>e is Map && e['username']?.toString().toLowerCase()==target);if(already){if(mounted)setState(()=>error='Kontak ini sudah disimpan.');return;}await api.addContact(widget.session.token!,target,name.text.trim().isEmpty?user!['displayName']?.toString()??target:name.text.trim());if(mounted)Navigator.pop(context,true);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>saving=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Tambah kontak')),body:ListView(padding:const EdgeInsets.all(20),children:[TextField(controller:username,decoration:const InputDecoration(labelText:'Username',prefixText:'@',hintText:'username target'),onSubmitted:(_)=>find()),const SizedBox(height:12),FilledButton(onPressed:searching?null:find,child:searching?const SizedBox(width:20,height:20,child:CircularProgressIndicator(strokeWidth:2)):const Text('Cari pengguna')),if(error!=null)Padding(padding:const EdgeInsets.only(top:14),child:Text(error!,style:const TextStyle(color:Colors.redAccent))),if(user!=null)...[const SizedBox(height:20),ListTile(leading:CircleAvatar(child:Text((user!['displayName']??user!['username'])[0].toString().toUpperCase())),title:Row(children:[Text(user!['displayName']??user!['username']),if(user!['verified']==true)const Padding(padding:EdgeInsets.only(left:5),child:VerifiedBadge())]),subtitle:Text('@${user!['username']}')),const SizedBox(height:12),TextField(controller:name,decoration:const InputDecoration(labelText:'Nama kontak',hintText:'Nama yang ingin ditampilkan')),const SizedBox(height:20),FilledButton(onPressed:saving?null:save,child:Text(saving?'Menyimpan...':'Simpan kontak'))]]));}
