import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:video_player/video_player.dart';
import '../services/api.dart';
import '../services/session.dart';
import '../services/socket_service.dart';
import '../utils/db.dart';
import '../widgets/verified_badge.dart';
import 'group_pages.dart';

class GroupChatPage extends StatefulWidget {
  final Session session; final Map<String, dynamic> group;
  const GroupChatPage({super.key, required this.session, required this.group});
  @override State<GroupChatPage> createState() => _GroupChatPageState();
}

class _GroupChatPageState extends State<GroupChatPage> {
  final api=Api(), socket=SocketService(), input=TextEditingController(), scroll=ScrollController(), picker=ImagePicker();
  final messages=<Map<String,dynamic>>[], downloaded=<String,String>{};
  Timer? poll, typingTimer; bool syncing=false, sending=false, remoteTyping=false; String? lastCursor; late Map<String,dynamic> group;
  @override void initState(){super.initState();group=Map<String,dynamic>.from(widget.group);input.addListener(_onInput);_connect();_load();poll=Timer.periodic(const Duration(seconds:8),(_){if(!socket.connected)_connect();if(socket.connected)_sync();});}
  void _connect(){if(widget.session.token==null)return;socket.connect(Api.baseUrl,widget.session.token!);socket.on('group:message:new',_onMessage);socket.on('group:typing',_onTyping);socket.on('group:updated',_onUpdated);}
  void _onUpdated(dynamic raw){if(raw is Map&&raw['group'] is Map&&raw['group']['id']?.toString()==group['id']?.toString()&&mounted)setState(()=>group=Map<String,dynamic>.from(raw['group']));}
  void _onTyping(dynamic raw){if(raw is! Map||raw['groupId']?.toString()!=group['id']?.toString()||raw['from']?.toString()==widget.session.username)return;final v=raw['typing']==true;if(mounted&&remoteTyping!=v)setState(()=>remoteTyping=v);}
  void _onMessage(dynamic raw){if(raw is! Map||raw['groupId']?.toString()!=group['id']?.toString())return;_merge([Map<String,dynamic>.from(raw)]);if(mounted)setState((){});_bottom();}
  Future<void> _load()async{final local=await LocalCache.messages('group_${group['id']}');if(local.isNotEmpty){messages.addAll(local);if(mounted)setState((){});}await _sync(full:true);await _markRead();_bottom(jump:true);}
  Future<void> _sync({bool full=false})async{if(syncing||widget.session.token==null)return;syncing=true;try{final rows=await api.groupMessages(widget.session.token!,group['id'].toString(),since:full?null:lastCursor);_merge(rows.map((e)=>Map<String,dynamic>.from(e)).toList());if(messages.isNotEmpty)lastCursor=messages.last['createdAt']?.toString();await LocalCache.saveMessages('group_${group['id']}',messages);if(mounted)setState((){});}catch(_){}finally{syncing=false;}}
  void _merge(List<Map<String,dynamic>> rows){final map=<String,Map<String,dynamic>>{for(final m in messages)m['id'].toString():m};for(final m in rows){final id=m['id']?.toString();if(id!=null)map[id]={...map[id]??{},...m};}messages..clear()..addAll(map.values)..sort((a,b)=>(DateTime.tryParse(a['createdAt']?.toString()??'')??DateTime(0)).compareTo(DateTime.tryParse(b['createdAt']?.toString()??'')??DateTime(0)));}
  Future<void> _markRead()async{try{await api.markGroupRead(widget.session.token!,group['id'].toString());}catch(_) {}}
  void _onInput(){final active=input.text.trim().isNotEmpty;socket.emit('group:typing',{'groupId':group['id'],'typing':active});typingTimer?.cancel();if(active)typingTimer=Timer(const Duration(milliseconds:1200),()=>socket.emit('group:typing',{'groupId':group['id'],'typing':false}));}
  Future<void> _sendText()async{final text=input.text.trim();if(text.isEmpty)return;input.clear();socket.emit('group:typing',{'groupId':group['id'],'typing':false});final temp={'id':'local-${DateTime.now().microsecondsSinceEpoch}','groupId':group['id'],'type':'text','message':text,'senderUsername':widget.session.username,'createdAt':DateTime.now().toUtc().toIso8601String(),'status':'sending'};messages.add(temp);setState((){});_bottom();try{final r=await api.sendGroupMessage(widget.session.token!,group['id'].toString(),text);_merge([r]);await LocalCache.saveMessages('group_${group['id']}',messages);if(mounted)setState((){});}catch(_){final i=messages.indexWhere((m)=>m['id']==temp['id']);if(i>=0)messages[i]={...messages[i],'status':'failed'};if(mounted)setState((){});}}
  Future<void> _pickMedia(bool video)async{final x=video?await picker.pickVideo(source:ImageSource.gallery,maxDuration:const Duration(minutes:10)):await picker.pickImage(source:ImageSource.gallery,imageQuality:92,maxWidth:2400,maxHeight:2400);if(x==null)return;final f=File(x.path);if(!await f.exists())return;if(await f.length()>50*1024*1024){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Maksimal 50 MB.')));return;}setState(()=>sending=true);try{final r=await api.uploadGroupMedia(widget.session.token!,group['id'].toString(),f,type:video?'video':'image');_merge([r]);await LocalCache.saveMessages('group_${group['id']}',messages);if(mounted)setState((){});_bottom();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Gagal mengirim media: $e')));}finally{if(mounted)setState(()=>sending=false);}}
  Future<void> _download(Map<String,dynamic> m)async{final id=m['id']?.toString()??'';if(id.isEmpty||downloaded.containsKey(id))return;try{final r=await api.downloadMedia(widget.session.token!,id);if(r.statusCode!=200)throw Exception();final dir=await Directory.systemTemp.createTemp('xchat_media');final path='${dir.path}/${m['fileName']??'media_$id'}';await File(path).writeAsBytes(r.bodyBytes,flush:true);downloaded[id]=path;if(mounted)setState((){});}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Media belum tersedia.')));}}
  void _bottom({bool jump=false}){WidgetsBinding.instance.addPostFrameCallback((_){if(!scroll.hasClients)return;final t=scroll.position.maxScrollExtent;if(jump)scroll.jumpTo(t);else scroll.animateTo(t,duration:const Duration(milliseconds:140),curve:Curves.easeOut);});}
  String _time(dynamic v){final d=DateTime.tryParse(v?.toString()??'')?.toLocal();return d==null?'':'${d.hour.toString().padLeft(2,'0')}:${d.minute.toString().padLeft(2,'0')}';}
  String _memberSubtitle(){final members=List<dynamic>.from(group['members']??const []);return members.map((e)=>(e['name']??e['username']).toString()).take(4).join(', ');}
  Widget _avatar(Map<String,dynamic> m){final a=(m['senderAvatarUrl']??'').toString();final n=(m['senderName']??m['senderUsername']??'?').toString();return CircleAvatar(radius:14,backgroundImage:a.isNotEmpty?NetworkImage(a):null,child:a.isEmpty?Text(n.isEmpty?'?':n[0].toUpperCase(),style:const TextStyle(fontSize:11)):null);}
  Widget _bubble(Map<String,dynamic> m){
    final mine=m['senderUsername']==widget.session.username; final type=m['type']?.toString()??'text'; final name=(m['senderName']??m['senderUsername']??'').toString();
    Widget content;
    if(type=='image'||type=='video'){
      final id=m['id'].toString(); final path=downloaded[id];
      content=GestureDetector(onTap:()=>_openMedia(m),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:300,maxHeight:360),child:ClipRRect(borderRadius:BorderRadius.circular(15),child:path!=null?(type=='video'?_InlineVideo(path:path):Image.file(File(path),fit:BoxFit.contain)):Container(width:250,height:180,color:Colors.black26,child:IconButton(onPressed:()=>_download(m),icon:const Icon(Icons.download_rounded,size:34))))));
    } else {
      content=Text(m['message']?.toString()??'',style:const TextStyle(fontSize:15));
    }
    final footer=Row(mainAxisAlignment:MainAxisAlignment.end,children:[Text(_time(m['createdAt']),style:const TextStyle(fontSize:10,color:Colors.white54)),if(mine) ...[const SizedBox(width:3),Icon(m['status']=='failed'?Icons.close:m['status']=='read'?Icons.done_all:Icons.done,size:15,color:m['status']=='read'?const Color(0xFF64B5F6):Colors.white54)]]);
    final children=<Widget>[];
    if(!mine) children.add(Row(children:[_avatar(m),const SizedBox(width:7),Flexible(child:Text(name,style:const TextStyle(color:Color(0xFF75D6A0),fontSize:12,fontWeight:FontWeight.w800))),if(m['senderVerified']==true)const Padding(padding:EdgeInsets.only(left:4),child:VerifiedBadge(size:13))]));
    if(!mine) children.add(const SizedBox(height:5));
    children.add(content); children.add(footer);
    return Align(alignment:mine?Alignment.centerRight:Alignment.centerLeft,child:Container(constraints:BoxConstraints(maxWidth:MediaQuery.sizeOf(context).width*.82),margin:const EdgeInsets.only(bottom:6),padding:const EdgeInsets.fromLTRB(10,8,8,6),decoration:BoxDecoration(color:mine?const Color(0xFF2A6B55):const Color(0xFF20282C),borderRadius:BorderRadius.circular(13)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:children)));
  }
  Future<void> _openMedia(Map<String,dynamic> m)async{final id=m['id'].toString();if(!downloaded.containsKey(id))await _download(m);final path=downloaded[id];if(path==null||!mounted)return;await Navigator.push(context,MaterialPageRoute(builder:(_)=>_GroupMediaViewer(path:path,video:m['type']=='video')));}
  Future<void> _showInfo()async{final changed=await Navigator.push(context,MaterialPageRoute(builder:(_)=>GroupInfoPage(session:widget.session,groupId:group['id'].toString())));if(changed==true&&mounted)Navigator.pop(context,true);}
  @override void dispose(){poll?.cancel();typingTimer?.cancel();socket.emit('group:typing',{'groupId':group['id'],'typing':false});socket.disconnect();input.dispose();scroll.dispose();super.dispose();}
  @override Widget build(BuildContext context){return Scaffold(backgroundColor:const Color(0xFF080D10),appBar:AppBar(backgroundColor:const Color(0xFF10171A),title:InkWell(onTap:_showInfo,child:Row(children:[CircleAvatar(radius:18,backgroundColor:const Color(0xFF2D2039),backgroundImage:(group['avatarUrl']??'').toString().isNotEmpty?NetworkImage(group['avatarUrl'].toString()):null,child:(group['avatarUrl']??'').toString().isEmpty?Text(group['name'].toString().isEmpty?'?':group['name'].toString()[0].toUpperCase()):null),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(group['name'].toString(),style:const TextStyle(fontSize:16,fontWeight:FontWeight.w800),overflow:TextOverflow.ellipsis),AnimatedSwitcher(duration:const Duration(milliseconds:180),child:remoteTyping?const Text('Mengetik...',style:TextStyle(fontSize:11,color:Color(0xFF5FD18A))):Text(_memberSubtitle(),style:const TextStyle(fontSize:11,color:Colors.white54)))]))])),actions:[IconButton(onPressed:_showInfo,icon:const Icon(Icons.info_outline_rounded))]),body:Stack(children:[Positioned.fill(child:Container(decoration:const BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Color(0xFF0D1519),Color(0xFF080D10)])))),Positioned.fill(child:ListView.builder(controller:scroll,padding:const EdgeInsets.fromLTRB(10,14,10,95),itemCount:messages.length,itemBuilder:(_,i)=>_bubble(messages[i]))),Positioned(left:0,right:0,bottom:0,child:SafeArea(top:false,child:_composer()))]));}
  Widget _composer()=>Container(padding:const EdgeInsets.fromLTRB(8,8,8,7),color:const Color(0xEE10171A),child:Row(children:[IconButton(onPressed:sending?null:()=>showModalBottomSheet(context:context,backgroundColor:const Color(0xFF10171A),builder:(c)=>SafeArea(child:Wrap(children:[ListTile(leading:const Icon(Icons.photo_outlined),title:const Text('Foto'),onTap:(){Navigator.pop(c);_pickMedia(false);}),ListTile(leading:const Icon(Icons.videocam_outlined),title:const Text('Video'),onTap:(){Navigator.pop(c);_pickMedia(true);})]))),icon:const Icon(Icons.add_circle_outline)),Expanded(child:TextField(controller:input,minLines:1,maxLines:5,decoration:InputDecoration(hintText:'Pesan grup',filled:true,fillColor:const Color(0xFF1B2529),border:OutlineInputBorder(borderSide:BorderSide.none,borderRadius:BorderRadius.circular(22)),contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:11)))),const SizedBox(width:5),Material(color:const Color(0xFF20C76B),shape:const CircleBorder(),child:InkWell(onTap:sending?null:_sendText,customBorder:const CircleBorder(),child:const Padding(padding:EdgeInsets.all(12),child:Icon(Icons.send_rounded,color:Colors.black,size:21))))]));
}

class _InlineVideo extends StatefulWidget{final String path;const _InlineVideo({required this.path});@override State<_InlineVideo> createState()=>_InlineVideoState();}
class _InlineVideoState extends State<_InlineVideo>{late VideoPlayerController c;@override void initState(){super.initState();c=VideoPlayerController.file(File(widget.path))..initialize().then((_){if(mounted)setState((){});});}@override void dispose(){c.dispose();super.dispose();}@override Widget build(BuildContext context){if(!c.value.isInitialized)return const SizedBox(width:250,height:180,child:Center(child:CircularProgressIndicator()));return Stack(alignment:Alignment.center,children:[AspectRatio(aspectRatio:c.value.aspectRatio,child:VideoPlayer(c)),IconButton(onPressed:(){setState(()=>c.value.isPlaying?c.pause():c.play());},icon:Icon(c.value.isPlaying?Icons.pause_circle_filled:Icons.play_circle_fill,size:52,color:Colors.white))]);}}
class _GroupMediaViewer extends StatelessWidget{final String path;final bool video;const _GroupMediaViewer({required this.path,required this.video});@override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(backgroundColor:Colors.black),body:Center(child:video?VideoPlayerView(path:path):InteractiveViewer(constrained:false,clipBehavior:Clip.none,minScale:.5,maxScale:6,child:Image.file(File(path)))));}
class VideoPlayerView extends StatefulWidget{final String path;const VideoPlayerView({super.key,required this.path});@override State<VideoPlayerView> createState()=>_VideoPlayerViewState();}
class _VideoPlayerViewState extends State<VideoPlayerView>{late VideoPlayerController c;@override void initState(){super.initState();c=VideoPlayerController.file(File(widget.path))..initialize().then((_){if(mounted){setState((){});c.play();}});}@override void dispose(){c.dispose();super.dispose();}@override Widget build(BuildContext context)=>c.value.isInitialized?Center(child:Stack(alignment:Alignment.center,children:[AspectRatio(aspectRatio:c.value.aspectRatio,child:VideoPlayer(c)),IconButton(onPressed:(){setState(()=>c.value.isPlaying?c.pause():c.play());},icon:Icon(c.value.isPlaying?Icons.pause_circle:Icons.play_circle,size:60,color:Colors.white))])):const Center(child:CircularProgressIndicator());}
